### ISSUE TITLE
Unprocessible Entity

### ISSUE THREAD

**Issue by jzelinskie** [bufbuild/buf-breaking-action#4]
Our action might be misconfigured, but it's failing to run with this error and this config:

>Failed to write comments in-line: Unprocessable Entity: "Pull request review thread path is invalid and Pull request review thread diff hunk can't be blank"

```yaml
    ...
    - uses: bufbuild/buf-breaking-action@v0.2.0
      if: github.event_name == 'pull_request'
      env:
        BUF_INPUT_HTTPS_USERNAME: "${{ github.actor }}"
        BUF_INPUT_HTTPS_PASSWORD: "${{ github.token }}"
      with:
        input: "./dirthatcontainsbufyaml"
        against: "https://github.com/organization/repository.git#branch=master"
        github_token: "${{ github.token }}"
        buf_token: "${{ secrets.BUF_TOKEN }}"
```

**Comment by amckinney** [comment]
At first glance, it looks like you're targeting a nested directory input (`./dirthatcontainsbufyaml`), but aren't including that in your `--against` reference. You can use the `subdir` parameter for that, so you would have the following (this is explained in greater detail in the [README.md](https://github.com/bufbuild/buf-breaking-action#inputs)):

```yaml
    ...
    - uses: bufbuild/buf-breaking-action@v0.2.0
      if: github.event_name == 'pull_request'
      env:
        BUF_INPUT_HTTPS_USERNAME: "${{ github.actor }}"
        BUF_INPUT_HTTPS_PASSWORD: "${{ github.token }}"
      with:
        input: "dirthatcontainsbufyaml"
        against: "https://github.com/organization/repository.git#branch=master,subdir=dirthatcontainsbufyaml"
        github_token: "${{ github.token }}"
        buf_token: "${{ secrets.BUF_TOKEN }}"
```

Regardless, the error message clearly isn't very helpful - I'll see what we can do to clean that up. Let me know if this works for you! Otherwise, I'll keep investigating and try to reproduce your error to see what's going wrong.
