### ISSUE TITLE
buf-breaking-action issue with subdirectory option

### ISSUE THREAD

**Issue by sybo-raphael** [bufbuild/buf-breaking-action#66]
Hi there 👋 

I've just added github actions for automated protobuf checks for PRs in a private repository (sorry cannot share).
Here is the hierarchy of the repo:
```sh
$ tree
.
└── proto
    ├── service
    │   └── v1
    │        └── service.proto
    └── buf.yaml
```
And this is my protobuf github action yaml file:
```yaml
name: protobuf-checks
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v1
      - uses: bufbuild/buf-lint-action@v1
        with:
          input: "proto"
      - uses: bufbuild/buf-breaking-action@v1
        with:
          input: "proto"
          against: "https://github.com/${GITHUB_REPOSITORY}.git#branch=master,ref=HEAD~1,subdir=proto"
```
And here goes the github actions error logs:
```text
Run bufbuild/buf-breaking-action@v1
  with:
    input: proto
    against: https://github.com/${GITHUB_REPOSITORY}.git#branch=master,ref=HEAD~1,subdir=proto
    buf_input_https_username: ...
    buf_input_https_password: ***
Failure: no .proto target files found
Error: Failure: no .proto target files found
```
Not 100% sure I didn't miss anything so sorry in advance if its the case.
