### ISSUE TITLE
Comments are not created when breaking changes happen

### ISSUE THREAD

**Issue by toshi0607** [bufbuild/buf-breaking-action#91]
Hi! Thank you for useful action! When I try this action, a comment about breaking change is not created though a breaking change is detected. Would you help find the cause?

## Settings

```yaml
  breaking:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3

      - name: Set up Buf
        uses: bufbuild/buf-setup-action@v1.18.0
        with:
          version: ${{ env.BUF_VERSION }}

      - name: Check breaking changes
        uses: bufbuild/buf-breaking-action@v1
        with:
          input: schema/proto
          against: https://github.com/xxx/yyy.git#branch=main,subdir=schema/proto
```

## Output

```shell
Run bufbuild/buf-breaking-action@v1
  with:
    input: schema/proto
    against: https://github.com/xxx/yyy.git#branch=main,subdir=schema/proto
    buf_input_https_username: toshi0607
    buf_input_https_password: ***
  env:
    BUF_VERSION: 1.18.0
Error: Previously present field "[3](https://github.com/xxx/yyy/actions/runs/nnnn/jobs/mmmm#step:4:3)" with name "request_time" on message "HelloResponse" was deleted.
Error: buf found 1 breaking changes.
```
