### ISSUE TITLE
buf breaking action not working in private repo

### ISSUE THREAD

**Issue by ehrktia** [bufbuild/buf-breaking-action#92]
hi,
I have a private repo in the organisation, when I tried to run the `buf-breaking` action it is failing with no details in the GitHub action.
reference - https://github.com/bufbuild/buf-breaking-action/issues/65
based on the reference issue which is closed the action is set up as below.
```
      - name: check change
        uses: sede-open/buf-breaking-action@main
        with:
          input: protos
          against: https://github.com/org/${{ github.repository }}.git#format=git,ref=main,branch=main,ref=HEAD~1,subdir=protos

```
error message:
```
   with:
    input: protos
    against: https://github.com/org/repo_name.git#format=git,branch=main,ref=HEAD~1,subdir=protos
    buf_input_https_username: ehrktia
    buf_input_https_password: ***
```
as per reference the issue seems to be resolved in buf slack channel.
Would it be possible to provide the details on how is resolved / solution provided
